# **Basic Python**

## 1.a 
Give a function F that takes a single argument n. This function should print a sequence of n strings as described in the examples below: <br>
Ex: **n = 3**

--A--<br>
-BAB-<br>
CBABC<br>

**n = 4**

---A---<br>
--BAB--<br>
-CBABC-<br>
DCBABCD

In [1]:

def F(n):
    def s(n):
        result = ''  # Initialize an empty string
        for i in range(n):
            result += chr(65 + i)  # add the characters
        return result  

    def Row(x):
        # create the mirrored string (without repeating the center character)
        mirror = x + x[-2::-1]  
        return mirror

    # now the loop to generate the pattern
    for i in range(1, n + 1):
        base_seq = s(i)
        
        mirrored_seq = Row(base_seq)
        dashes = "-" * (n - i)
        print(f"{dashes}{mirrored_seq}{dashes}")

# Tests
F(10)
F(6)

---------A---------
--------ABA--------
-------ABCBA-------
------ABCDCBA------
-----ABCDEDCBA-----
----ABCDEFEDCBA----
---ABCDEFGFEDCBA---
--ABCDEFGHGFEDCBA--
-ABCDEFGHIHGFEDCBA-
ABCDEFGHIJIHGFEDCBA
-----A-----
----ABA----
---ABCBA---
--ABCDCBA--
-ABCDEDCBA-
ABCDEFEDCBA


## 1.b
Make a function F that takes only one argument, a dictionary(dict) d.
The keys of d are integers and the values of d are a tuple of type (x (int), y (int)).
You must print out the dict in the format "-key-, -x-, -y-" with each entry in a new line. Print it for each of the three sorted orders, by key values ascending, by x values descending, by y values ascending.

In [2]:
def F(d : dict):
    # key values ascending
    print("Sorted by key (ascending):")
    for key in sorted(d.keys()):
        x, y = d[key]
        print(f"{key}, {x}, {y}")

    # x values descending
    print("\nSorted by x (descending):")
    for key, (x, y) in sorted(d.items(), key=lambda item: item[1][0], reverse=True):
        print(f"{key}, {x}, {y}")

    # y values ascending
    print("\nSorted by y (ascending):")
    for key, (x, y) in sorted(d.items(), key=lambda item: item[1][1]):
        print(f"{key}, {x}, {y}")

# Tests
F({1 : (1, 2), 2 : (-1, 4), 5 : (-4, 3), 4 : (2, 3)})
F({-8 : (4, 2), 6 : (-3, 4), 7 : (2, 1), 5 : (9, -10)})

Sorted by key (ascending):
1, 1, 2
2, -1, 4
4, 2, 3
5, -4, 3

Sorted by x (descending):
4, 2, 3
1, 1, 2
2, -1, 4
5, -4, 3

Sorted by y (ascending):
1, 1, 2
5, -4, 3
4, 2, 3
2, -1, 4
Sorted by key (ascending):
-8, 4, 2
5, 9, -10
6, -3, 4
7, 2, 1

Sorted by x (descending):
5, 9, -10
-8, 4, 2
7, 2, 1
6, -3, 4

Sorted by y (ascending):
5, 9, -10
7, 2, 1
-8, 4, 2
6, -3, 4


## 2 Working with Student Records

Use the data in **student_records.csv** to complete the given tasks. Do not include any external libraries. Use a Python dictionary if required.

### Reference
- [Python Dictionaries](https://www.w3schools.com/python/python_dictionaries.asp)


#### 2.a: open the student_records.csv file and print out the first 10 rows

In [3]:
#TODO
with open("student_records.csv", "r") as file:
    rows = file.readlines()  # Read all lines into a list
    header = rows[0].strip().split(",")  # First row as header
    student_data = [row.strip().split("\n") for row in rows[1:]]  # Remaining rows as data
    for i, row in enumerate(rows[:10]):  # Limit to the first 10 rows
        print(f"Row {i + 1}: {row.strip()}")


Row 1: roll_number,department,credit,course_name,course_type,grade
Row 2: 588946,MA,3,EC250,hasmed_elective,AB
Row 3: 145372,EP,4,EP407,hasmed_elective,CC
Row 4: 834515,MA,8,EP885,hasmed_elective,BB
Row 5: 344265,CSE,6,CSE699,honours,AB
Row 6: 358405,MA,3,EE460,minor,AP
Row 7: 781075,CE,8,CE540,honours,CC
Row 8: 180828,CSE,6,CE880,minor,AB
Row 9: 981238,MM,4,CSE226,minor,AB
Row 10: 836881,MM,8,MM530,core,AA


#### 2.b: Print out the total credits and calculte CPI of each student. 
CPI is the weighted average of core courses, and electives (weights being the letter grades converted to number AP,AA=10, AB=9, BB=9, BC=7, CC=6)

In [4]:
with open("student_records.csv", "r") as file:
    rows = file.readlines()  # Read all lines into a list
    header = rows[0].strip().split(",")  # First row as header
    student_data = [dict(zip(header, row.strip().split(","))) for row in rows[1:]]  # Map header to row values

def calculate_cpi_and_credits(student_data):
    """
    Calculates total credits and CPI for each student.
    """
    grade_points = {"AP": 10, "AA": 10, "AB": 9, "BB": 8, "BC": 7, "CC": 6}
    roll_to_data = {}

    for record in student_data:
        roll = record["roll_number"]
        if roll not in roll_to_data:
            roll_to_data[roll] = {"total_credits": 0, "weighted_grades": 0, "course_count": 0}
        
        credit = int(record["credit"])
        grade = record["grade"]
        
        if grade in grade_points:
            weight = grade_points[grade]
            roll_to_data[roll]["total_credits"] += credit
            roll_to_data[roll]["weighted_grades"] += weight * credit
            roll_to_data[roll]["course_count"] += 1

    for roll, data in roll_to_data.items():
        total_credits = data["total_credits"]
        weighted_grades = data["weighted_grades"]
        cpi = round(weighted_grades / total_credits, 2) if total_credits > 0 else 0
        print(f"Roll Number: {roll}, Total Credits: {total_credits}, CPI: {cpi}")

calculate_cpi_and_credits(student_data)

Roll Number: 588946, Total Credits: 199, CPI: 8.69
Roll Number: 145372, Total Credits: 173, CPI: 7.75
Roll Number: 834515, Total Credits: 199, CPI: 8.22
Roll Number: 344265, Total Credits: 153, CPI: 8.7
Roll Number: 358405, Total Credits: 206, CPI: 8.59
Roll Number: 781075, Total Credits: 246, CPI: 8.17
Roll Number: 180828, Total Credits: 177, CPI: 8.1
Roll Number: 981238, Total Credits: 168, CPI: 8.24
Roll Number: 836881, Total Credits: 246, CPI: 8.39
Roll Number: 310604, Total Credits: 198, CPI: 8.33
Roll Number: 847809, Total Credits: 261, CPI: 8.21
Roll Number: 773982, Total Credits: 264, CPI: 8.07
Roll Number: 500658, Total Credits: 208, CPI: 8.17
Roll Number: 810863, Total Credits: 192, CPI: 8.15
Roll Number: 124663, Total Credits: 229, CPI: 8.13
Roll Number: 364146, Total Credits: 225, CPI: 8.4
Roll Number: 871746, Total Credits: 216, CPI: 8.21
Roll Number: 270007, Total Credits: 241, CPI: 8.03
Roll Number: 597353, Total Credits: 200, CPI: 8.12
Roll Number: 986057, Total Credits

#### 2.c: Print out the names of all students who meet the graduation requirements 
Atleast 20 credist of core course, 15 credits of department elective, 10 credits of flexible elective and 5 credits of hasmed electives

In [5]:
with open("student_records.csv", "r") as file:
    rows = file.readlines()  # Read all lines from the file

student_data = [row.strip().split(",") for row in rows[1:]]  # Skip the header and split each row

def graduation_requirements(student_data):
        
    # Organize by student
    students = {}
    for row in student_data:
        roll_number, department, credit, course_name, course_type, grade = row
        credit = int(credit)  # Convert credit to integer
        
        if roll_number not in students:
            students[roll_number] = []

        students[roll_number].append({
            "credit": credit,
            "course_type": course_type,
            "grade": grade
        })

    
    graduates = []
    for roll_number, courses in students.items():
        core_credits = sum(course["credit"] for course in courses if course["course_type"] == "core")
        department_elective_credits = sum(course["credit"] for course in courses if course["course_type"] == "department_elective")
        felxible_elective_credits = sum(course["credit"] for course in courses if course["course_type"] == "felxible_elective")
        hasmed_credits = sum(course["credit"] for course in courses if course["course_type"] == "hasmed_elective")

        if (core_credits >= 20 and 
            department_elective_credits >= 15 and 
            felxible_elective_credits >= 10 and 
            hasmed_credits >= 5):
            graduates.append(roll_number)

    print("Students who meet graduation requirements:")
    for roll_number in graduates:
        print(f"  Roll Numbers: {roll_number}")


graduation_requirements(student_data)

Students who meet graduation requirements:
  Roll Numbers: 588946
  Roll Numbers: 834515
  Roll Numbers: 781075
  Roll Numbers: 180828
  Roll Numbers: 981238
  Roll Numbers: 836881
  Roll Numbers: 310604
  Roll Numbers: 773982
  Roll Numbers: 500658
  Roll Numbers: 810863
  Roll Numbers: 124663
  Roll Numbers: 871746
  Roll Numbers: 986057
  Roll Numbers: 379479
  Roll Numbers: 144528
  Roll Numbers: 485484
  Roll Numbers: 845623
  Roll Numbers: 150503
  Roll Numbers: 214270
  Roll Numbers: 517837
  Roll Numbers: 482623
  Roll Numbers: 721490
  Roll Numbers: 955757
  Roll Numbers: 143856
  Roll Numbers: 571782
  Roll Numbers: 973158
  Roll Numbers: 703403
  Roll Numbers: 960395
  Roll Numbers: 521087
  Roll Numbers: 461971
  Roll Numbers: 879634
  Roll Numbers: 716985
  Roll Numbers: 265922
  Roll Numbers: 283796
  Roll Numbers: 203200
  Roll Numbers: 327122
  Roll Numbers: 534763
  Roll Numbers: 391848
  Roll Numbers: 971123
  Roll Numbers: 207443
  Roll Numbers: 488661
  Roll Numbers

#### 2.d: Print out the names of all students who completed a minor 
Atleast 10 credits with minor tag in a specific department

In [6]:
def minor_completion(student_data):
    # same thing reading the CSV file
    with open("student_records.csv", "r") as file:
        rows = file.readlines()

    header = rows[0].strip().split(",")  # Extract the header
    data = [row.strip().split(",") for row in rows[1:]]  # Extract data

    # student data
    students = {}
    for row in data:
        roll_number, department, credit, course_name, course_type, grade = row
        credit = int(credit)  # Convert credit to integer
        
        if roll_number not in students:
            students[roll_number] = []

        students[roll_number].append({
            "credit": credit,
            "course_type": course_type,
            "grade": grade
        })

    #now to check for completion of minor
    minors = []
    for roll_number, courses in students.items():
        minor_credits = sum(course["credit"] for course in courses if course["course_type"] == "minor")

        if minor_credits >= 10:  
            minors.append(roll_number)

    print("Students who completed a minor:")
    for roll_number in minors:
        print(f"  Roll Numbers: {roll_number}")

minor_completion(student_data)


Students who completed a minor:
  Roll Numbers: 588946
  Roll Numbers: 145372
  Roll Numbers: 834515
  Roll Numbers: 344265
  Roll Numbers: 358405
  Roll Numbers: 781075
  Roll Numbers: 180828
  Roll Numbers: 981238
  Roll Numbers: 836881
  Roll Numbers: 847809
  Roll Numbers: 773982
  Roll Numbers: 500658
  Roll Numbers: 810863
  Roll Numbers: 124663
  Roll Numbers: 364146
  Roll Numbers: 871746
  Roll Numbers: 270007
  Roll Numbers: 597353
  Roll Numbers: 986057
  Roll Numbers: 718510
  Roll Numbers: 836431
  Roll Numbers: 379479
  Roll Numbers: 582912
  Roll Numbers: 788020
  Roll Numbers: 613401
  Roll Numbers: 144528
  Roll Numbers: 485484
  Roll Numbers: 680096
  Roll Numbers: 199713
  Roll Numbers: 851029
  Roll Numbers: 845623
  Roll Numbers: 150503
  Roll Numbers: 214270
  Roll Numbers: 517837
  Roll Numbers: 482623
  Roll Numbers: 721490
  Roll Numbers: 955757
  Roll Numbers: 143856
  Roll Numbers: 571782
  Roll Numbers: 973158
  Roll Numbers: 703403
  Roll Numbers: 960395
  

#### 2.e: Print out the names of all students who completed a honours
Atleast 10 credits with honours tag and 20 core credits

In [7]:
def honors_completion():
    with open("student_records.csv", "r") as file:
        rows = file.readlines()

    header = rows[0].strip().split(",")  # Extract the header
    data = [row.strip().split(",") for row in rows[1:]]  # Extract data

    # student data
    students = {}
    for row in data:
        roll_number, department, credit, course_name, course_type, grade = row
        credit = int(credit)  # Convert credit to integer
        
        if roll_number not in students:
            students[roll_number] = []

        students[roll_number].append({
            "credit": credit,
            "course_type": course_type,
            "grade": grade
        })

    #now to check for completion of honor
    honors = []
    for roll_number, courses in students.items():
        honor_credits = sum(course["credit"] for course in courses if course["course_type"] == "honours")
        core_credits = sum(course["credit"] for course in courses if course["course_type"] == "core")
        if honor_credits >= 10 and core_credits >=20 :  
            honors.append(roll_number)

    print("Students who completed an honors in their department:")
    for roll_number in honors:
        print(f"  Roll Numbers: {roll_number}")


honors_completion()

Students who completed an honors in their department:
  Roll Numbers: 588946
  Roll Numbers: 145372
  Roll Numbers: 834515
  Roll Numbers: 781075
  Roll Numbers: 836881
  Roll Numbers: 310604
  Roll Numbers: 773982
  Roll Numbers: 500658
  Roll Numbers: 810863
  Roll Numbers: 124663
  Roll Numbers: 364146
  Roll Numbers: 871746
  Roll Numbers: 986057
  Roll Numbers: 718510
  Roll Numbers: 379479
  Roll Numbers: 582912
  Roll Numbers: 788020
  Roll Numbers: 613401
  Roll Numbers: 144528
  Roll Numbers: 485484
  Roll Numbers: 199713
  Roll Numbers: 845623
  Roll Numbers: 150503
  Roll Numbers: 214270
  Roll Numbers: 517837
  Roll Numbers: 482623
  Roll Numbers: 721490
  Roll Numbers: 955757
  Roll Numbers: 589528
  Roll Numbers: 143856
  Roll Numbers: 571782
  Roll Numbers: 973158
  Roll Numbers: 703403
  Roll Numbers: 960395
  Roll Numbers: 521087
  Roll Numbers: 461971
  Roll Numbers: 879634
  Roll Numbers: 716985
  Roll Numbers: 265922
  Roll Numbers: 283796
  Roll Numbers: 203200
  R

# **SciPy** 

## Part A
Minimize the function $f(x, y) = 2(x - y - 3)^2 + 4(x + 2y + 1)^4$.<br>
With the constraints : $ x - y \ge -3, (x + 2)^2 + (y + 1)^2 \le 5$ <br>
Using scipy.optimize.minimize with constraints. (Hint: Look at the examples in the official documentation)

In [8]:
%pip install numpy scipy
import numpy as np
from scipy.optimize import minimize

def f(x):
    return 2*(x[0] - x[1] - 3)**2 + 4*(x[0] + 2*x[1] + 1)**4

# Define the constraints
def constraint1(x):
    return x[0] - x[1] + 3  # x - y >= -3, or x - y + 3 >= 0

def constraint2(x):
    return 5 - (x[0] + 2)**2 - (x[1] + 1)**2  # (x + 2)^2 + (y + 1)^2 <= 5

# Initial guess for the optimization variables
x0 = [0, 0]

# Define the constraints in the format needed for minimize
con1 = {'type': 'ineq', 'fun': constraint1}  # Linear constraint: x - y + 3 >= 0
con2 = {'type': 'ineq', 'fun': constraint2}  # Nonlinear constraint: (x + 2)^2 + (y + 1)^2 <= 5

result = minimize(f, x0, constraints=[con1, con2])

print(f"Optimal solution: x = {result.x[0]}, y = {result.x[1]}")
print(f"Objective function value: {result.fun}")
print(f"Success: {result.success}")
print(f"Message: {result.message}")


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Optimal solution: x = 0.2349250274647683, y = -0.9285148850646019
Objective function value: 7.345026216977383
Success: True
Message: Optimization terminated successfully


# Part B
Evaluate the line integral of the function $f(x, y) = x^2 + y^4$ along the circle $ x^2 + y^2 = 3 $ anticlockwise (scalar integral, not vector). You must use scipy for integration but you may use parameterization

In [9]:
import numpy as np
from scipy.integrate import quad

# Define the integrand
def integrand(t):
    return (3 * np.cos(t)**2 + 9 * np.sin(t)**4) * np.sqrt(3)

# Perform the integration over the interval [0, 2*pi]
result, error = quad(integrand, 0, 2 * np.pi)

print(f"Line integral result: {result}")
print(f"Estimated error: {error}")


Line integral result: 53.053631403850865
Estimated error: 5.3768447472180014e-09


# **Numpy**

### Read Lisan_Al_Gaib.pdf for problem description and complete the following functions

In [12]:
%pip install matplotlib
import time # to time the execution
import numpy as np
import matplotlib.pyplot as plt

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
### TODO 1
### Load data from data_path
### Check the input file spice_locations.txt to understand the Data Format
### Return : np array of size Nx2
data_path = 'spice_locations.txt'
data = np.loadtxt(data_path, delimiter=',')
def load_data(data_path):
    
    print("Loaded data:\n", data)
    print("Shape of data:", data.shape)
    
    return data
 
load_data(data_path)

Loaded data:
 [[-2.12729941e+00  1.75357153e+00]
 [-3.40030291e-01 -6.70757901e-03]
 [-3.21990680e+00 -2.22002740e+00]
 [-3.70958194e+00  1.33088073e+00]
 [-9.94424941e-01  5.40362889e-01]
 [-3.89707753e+00  1.84954926e+00]
 [ 1.62213204e-01 -1.93830445e+00]
 [-3.09087516e+00 -2.08297745e+00]
 [-2.47878879e+00 -3.76217842e-01]
 [-1.84027491e+00 -1.54385430e+00]
 [-9.40735526e-01 -2.30253070e+00]
 [-2.53927676e+00 -1.16819078e+00]
 [-1.71965008e+00  9.25879807e-01]
 [-3.00163109e+00 -4.28827808e-01]
 [-1.03792716e+00 -2.76774794e+00]
 [-9.62275740e-01 -2.14737938e+00]
 [-3.67474204e+00  1.74442769e+00]
 [ 8.28160165e-01  1.04198674e+00]
 [-2.47693115e+00 -2.51163943e+00]
 [-5.78834867e-01 -7.99237531e-01]
 [-3.38980883e+00 -5.24115449e-01]
 [-3.82805739e+00  1.54660201e+00]
 [-2.70610009e+00  3.12611422e-01]
 [-2.44144462e+00 -3.99659894e-01]
 [-1.26644860e+00 -2.07572772e+00]
 [ 8.47923139e-01  8.75664117e-01]
 [ 6.97494708e-01  1.47413675e+00]
 [-1.01050011e+00  1.60937118e+00]
 [-3.5

array([[-2.12729941e+00,  1.75357153e+00],
       [-3.40030291e-01, -6.70757901e-03],
       [-3.21990680e+00, -2.22002740e+00],
       [-3.70958194e+00,  1.33088073e+00],
       [-9.94424941e-01,  5.40362889e-01],
       [-3.89707753e+00,  1.84954926e+00],
       [ 1.62213204e-01, -1.93830445e+00],
       [-3.09087516e+00, -2.08297745e+00],
       [-2.47878879e+00, -3.76217842e-01],
       [-1.84027491e+00, -1.54385430e+00],
       [-9.40735526e-01, -2.30253070e+00],
       [-2.53927676e+00, -1.16819078e+00],
       [-1.71965008e+00,  9.25879807e-01],
       [-3.00163109e+00, -4.28827808e-01],
       [-1.03792716e+00, -2.76774794e+00],
       [-9.62275740e-01, -2.14737938e+00],
       [-3.67474204e+00,  1.74442769e+00],
       [ 8.28160165e-01,  1.04198674e+00],
       [-2.47693115e+00, -2.51163943e+00],
       [-5.78834867e-01, -7.99237531e-01],
       [-3.38980883e+00, -5.24115449e-01],
       [-3.82805739e+00,  1.54660201e+00],
       [-2.70610009e+00,  3.12611422e-01],
       [-2.

In [15]:
### TODO 2.1
### If init_centers is None, initialize the centers by selecting K data points at random without replacement
### Else, use the centers provided in init_centers
### Return : np array of size Kx2

def initialise_centers(data, K, init_centers=None):
    if init_centers is None:
        indices = np.random.choice(data.shape[0], K, replace=False) #random, no replacement
        centers = data[indices]
    else:
        centers = np.array(init_centers)
    
    print("Initial Centers:\n", centers)
    return centers
K=2
initialise_centers(data, K, init_centers=None)

Initial Centers:
 [[ 6.46279499  5.69671121]
 [ 0.1622132  -1.93830445]]


array([[ 6.46279499,  5.69671121],
       [ 0.1622132 , -1.93830445]])

In [16]:
### TODO 2.2
### Initialize the labels to all ones to size (N,) where N is the number of data points
### Return : np array of size N
def initialise_labels(data):
    N = data.shape[0]
    
    labels = np.ones(N, dtype=int)
    
    return labels

initialise_labels(data)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [17]:
### TODO 3.1 : E step
### For Each data point, find the distance to each center
### Return : np array of size NxK
centers = initialise_centers(data, K)
data = np.loadtxt(data_path, delimiter=',')
def calculate_distances(data, centers):
        differences = data[:, np.newaxis, :] - centers[np.newaxis, :, :]
        distances = np.sqrt(np.sum(differences**2, axis=2))
    
        return distances
distances = calculate_distances(data, centers)
print("Distances:\n", distances)

Initial Centers:
 [[ 0.84792314  0.87566412]
 [-3.09087516 -2.08297745]]
Distances:
 [[ 3.10204298  3.95570301]
 [ 1.47980173  3.44645384]
 [ 5.11180461  0.1882335 ]
 [ 4.58018282  3.46947053]
 [ 1.87261137  3.35812717]
 [ 4.84391201  4.01431546]
 [ 2.89631096  3.25630376]
 [ 4.92622492  0.        ]
 [ 3.55446489  1.81319555]
 [ 3.61669436  1.36185711]
 [ 3.64694696  2.16131999]
 [ 3.95606699  1.06822069]
 [ 2.56806422  3.30658135]
 [ 4.06457463  1.65655533]
 [ 4.10254588  2.16414097]
 [ 3.52357943  2.12957346]
 [ 4.60535019  3.87168317]
 [ 0.16749266  5.01240851]
 [ 4.74641774  0.74878457]
 [ 2.20021225  2.82105204]
 [ 4.46293122  1.5872656 ]
 [ 4.72387041  3.70368529]
 [ 3.59834816  2.42629304]
 [ 3.52794438  1.80424999]
 [ 3.63060348  1.82444096]
 [ 0.          4.92622492]
 [ 0.61708849  5.19661503]
 [ 1.99801477  4.23808905]
 [ 5.27194938  0.4708812 ]
 [ 5.13993865  0.98490944]
 [ 4.65830638  9.53681623]
 [ 6.58167045 11.507794  ]
 [ 5.47187665 10.14775322]
 [ 6.41010831 10.7836880

In [18]:
### TODO 3.2 : E step
### For Each data point, assign the label of the nearest center
### Return : np array of size N
def update_labels(distances):
    labels = np.argmin(distances, axis=1)
    return labels

data = load_data('spice_locations.txt')
K = 5 #playing around with this value
centers = initialise_centers(data, K)
distances = calculate_distances(data, centers)
labels = update_labels(distances)

print("Labels:", labels)

Loaded data:
 [[-2.12729941e+00  1.75357153e+00]
 [-3.40030291e-01 -6.70757901e-03]
 [-3.21990680e+00 -2.22002740e+00]
 [-3.70958194e+00  1.33088073e+00]
 [-9.94424941e-01  5.40362889e-01]
 [-3.89707753e+00  1.84954926e+00]
 [ 1.62213204e-01 -1.93830445e+00]
 [-3.09087516e+00 -2.08297745e+00]
 [-2.47878879e+00 -3.76217842e-01]
 [-1.84027491e+00 -1.54385430e+00]
 [-9.40735526e-01 -2.30253070e+00]
 [-2.53927676e+00 -1.16819078e+00]
 [-1.71965008e+00  9.25879807e-01]
 [-3.00163109e+00 -4.28827808e-01]
 [-1.03792716e+00 -2.76774794e+00]
 [-9.62275740e-01 -2.14737938e+00]
 [-3.67474204e+00  1.74442769e+00]
 [ 8.28160165e-01  1.04198674e+00]
 [-2.47693115e+00 -2.51163943e+00]
 [-5.78834867e-01 -7.99237531e-01]
 [-3.38980883e+00 -5.24115449e-01]
 [-3.82805739e+00  1.54660201e+00]
 [-2.70610009e+00  3.12611422e-01]
 [-2.44144462e+00 -3.99659894e-01]
 [-1.26644860e+00 -2.07572772e+00]
 [ 8.47923139e-01  8.75664117e-01]
 [ 6.97494708e-01  1.47413675e+00]
 [-1.01050011e+00  1.60937118e+00]
 [-3.5

In [19]:
### TODO 4 : M step
### Update the centers to the mean of the data points assigned to it
### Return : np array of size Kx2
def update_centers(data, labels, K):
    new_centers = np.zeros((K, data.shape[1]))  

    for k in range(K):
        cluster_points = data[labels == k]
        
        if cluster_points.size > 0:  
            new_centers[k] = np.mean(cluster_points, axis=0)

    return new_centers
update_centers(data, labels, K)

array([[ 5.69984604,  5.42820319],
       [ 2.9660099 ,  5.25237334],
       [-2.92923771, -2.27154809],
       [-3.69265446,  0.13491375],
       [-1.29164732, -0.27030351]])

In [20]:
### TODO 6 : Check convergence
### Check if the labels have changed from the previous iteration
### Return : True / False
def check_termination(labels1, labels2):
    def check_termination(labels1, labels2):
        return np.array_equal(labels1, labels2) #yes or no if they converged or not


In [21]:
### DON'T CHANGE ANYTHING IN THE FOLLOWING FUNCTION
def kmeans(data_path:str, K:int, init_centers):
    '''
    Input :
        data (type str): path to the file containing the data
        K (type int): number of clusters
        init_centers (type numpy.ndarray): initial centers. shape = (K, 2) or None
    Output :
        centers (type numpy.ndarray): final centers. shape = (K, 2)
        labels (type numpy.ndarray): label of each data point. shape = (N,)
        time (type float): time taken by the algorithm to converge in seconds
    N is the number of data points each of shape (2,)
    '''
    data = load_data(data_path)    
    centers = initialise_centers(data, K, init_centers)
    labels = initialise_labels(data)

    start_time = time.time() # Time stamp 

    while True:
        distances = calculate_distances(data, centers)
        labels_new = update_labels(distances)
        centers = update_centers(data, labels_new, K)
        if check_termination(labels, labels_new): break
        else: labels = labels_new
 
    end_time = time.time() # Time stamp after the algorithm ends
    return centers, labels, end_time - start_time 

In [22]:
### TODO 7
def visualise(data_path, labels, centers):
    data = load_data(data_path)

    # Scatter plot of the data points
    plt.scatter(data[:, 0], data[:, 1], c=labels, s=50, cmap='viridis')
    plt.scatter(centers[:, 0], centers[:, 1], c='black', s=200, alpha=0.5)

    ### Set title as 'K-means clustering'
    plt.title('K-means clustering')
    ### Set xlabel as 'Longitude'
    plt.xlabel('Longitude')
    ### Set ylabel as 'Latitude'
    plt.ylabel('Latitude')
    ### Save the plot as 'kmeans.png'
    plt.savefig('kmeans.png')

    ## DO NOT CHANGE THE FOLLOWING LINE
    return plt

In [ ]:
### After you have completed the above functions, run the following code to generate the plot
data_path = 'spice_locations.txt'
K, init_centers = 2, None
centers, labels, time_taken = kmeans(data_path, K, init_centers)
print('Time taken for the algorithm to converge:', time_taken)
visualise(data_path, labels, centers)

Loaded data:
 [[-2.12729941e+00  1.75357153e+00]
 [-3.40030291e-01 -6.70757901e-03]
 [-3.21990680e+00 -2.22002740e+00]
 [-3.70958194e+00  1.33088073e+00]
 [-9.94424941e-01  5.40362889e-01]
 [-3.89707753e+00  1.84954926e+00]
 [ 1.62213204e-01 -1.93830445e+00]
 [-3.09087516e+00 -2.08297745e+00]
 [-2.47878879e+00 -3.76217842e-01]
 [-1.84027491e+00 -1.54385430e+00]
 [-9.40735526e-01 -2.30253070e+00]
 [-2.53927676e+00 -1.16819078e+00]
 [-1.71965008e+00  9.25879807e-01]
 [-3.00163109e+00 -4.28827808e-01]
 [-1.03792716e+00 -2.76774794e+00]
 [-9.62275740e-01 -2.14737938e+00]
 [-3.67474204e+00  1.74442769e+00]
 [ 8.28160165e-01  1.04198674e+00]
 [-2.47693115e+00 -2.51163943e+00]
 [-5.78834867e-01 -7.99237531e-01]
 [-3.38980883e+00 -5.24115449e-01]
 [-3.82805739e+00  1.54660201e+00]
 [-2.70610009e+00  3.12611422e-01]
 [-2.44144462e+00 -3.99659894e-01]
 [-1.26644860e+00 -2.07572772e+00]
 [ 8.47923139e-01  8.75664117e-01]
 [ 6.97494708e-01  1.47413675e+00]
 [-1.01050011e+00  1.60937118e+00]
 [-3.5

taking forever to generate the graph, but it does work
